### ISSUE TITLE
🐛 Fail to initialize plugin after upgrade EverythingPT from 0.86.0 to 0.87.0

### ISSUE THREAD

**Issue by FahriDevZ** [lin-ycv/EverythingPowerToys#151] opened 2024-12-20 13:11 UTC
**Flight Check**
- [x ] I'm sure existing (open and closed) don't have duplicates
- [ ] I've tried reinstalling PT, Everything, EverythingPT

**Describe the bug**
Previously I had installed everythingpt 0.86.0 then I upgraded to 0.87.0 and the error appeared, because of this error I reinstalled version 0.86.0 without any problem, now I am still using 0.86.0 because I cannot run version 0.87.0

**To Reproduce**
1. exit powertoys
2. install from installer .exe
3. open powertoys

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/6d023378-0f95-47f5-bbbe-be829a4bed9e)

**Logs (please upload or provide link to you log):**
 Logs can be generated by right clicking the taskbar icon > Report Bug
or be found at
%localappdata%\Microsoft\PowerToys\PowerToys Run\Logs
[2024-12-20.txt](https://github.com/user-attachments/files/18210994/2024-12-20.txt)

**Version:**
 - PowerToy: 0.85.1.0
 - Everything: 1.4.1.1026 (x64)
 - EverythingPT: EverythingPT-0.87.0 x64
 - Windows: Windows 11 23H2 22631.4602 (x64)

 **Installation method (How did you install the following softwares):**
 - PowerToys: Windows Store
 - Everything: installer .exe
 - EverythingPT:  EverythingPT-0.87.0-x64.exe from github releases

**Additional context**

**Comment by lin-ycv** [comment] 2024-12-20 15:22
duplicate of #150, update your powertoys.

**Closed by lin-ycv** 2024-12-20 15:22 UTC
Labels: bug
