### ISSUE TITLE
[Request] Add powertoys and everything as dependencies in choco package

### ISSUE THREAD

**Issue by shvchk** [lin-ycv/EverythingPowerToys#55] opened 2023-08-31 17:20 UTC
**Is your feature request related to a problem? Please describe.**
When you install EverythingPowerToys package, no deps are installed, so it doesn't work ootb

**Describe the solution you'd like**
Install dependencies

**Describe alternatives you've considered**
Manual install. Not cool : )

**Comment by lin-ycv** [comment] 2023-09-01 01:14
Which dependencies are we talking about?

**Comment by shvchk** [comment] 2023-09-01 01:27
- https://community.chocolatey.org/packages/Everything
- https://community.chocolatey.org/packages/powertoys

**Comment by lin-ycv** [comment] 2023-09-01 01:52
Ah yes, sorry missed the title. Definitely can do for Choco package, will add it into v0.73.0

**Comment by lin-ycv** [comment] 2023-09-02 06:35
There seems to be some issue with listing powertoys as a dependency, as it will not install.
I'm removing the powertoys dependency for now until the issue is solved here:
https://github.com/mkevenaar/chocolatey-packages/issues/204

**Comment by lin-ycv** [comment] 2023-12-08 16:56
As there is no progress/response from the maintainer of the Powertoys package, I can only assume they will not be fixing (or it can't be fixed), so I'm closing this issue for now.

**Closed by lin-ycv** 2023-12-08 16:56 UTC
Labels: enhancement, NMP
