### ISSUE TITLE
v0.75失效了，可以修复嘛

### ISSUE THREAD

**Issue by freesimple** [lin-ycv/EverythingPowerToys#60] opened 2023-10-31 01:25 UTC
powertoys v0.75 插件失效了。
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/50224571/1c81e7bb-44aa-4545-acb1-6350fdd2e5d2)

**Comment by lin-ycv** [comment] 2023-10-31 05:04
有已修正的新版，但未發布

**Comment by crazy-zxx** [comment] 2023-10-31 06:44
期待新版本的修复！

**Comment by acdcbyl** [comment] 2023-10-31 07:45
期待大佬的修复

**Comment by DEAN-Cherry** [comment] 2023-10-31 11:03
> Using goole translator I understand that there's a upcoming release of the plugin to fix the error message. Please consider providing a short feedback on this message in English as would be a lot easier for international users to understand.

You have down this well :).

**Comment by lgander** [comment] 2023-10-31 11:36
Same problem here. Will be waiting for the new release. Thanks !

**Comment by madcowGit** [comment] 2023-10-31 13:32
Duplicate of #59

**Comment by lin-ycv** [comment] 2023-10-31 23:34
There is now a release for v0.75.1, it "works", but there's some minor buggy behaviours that I haven't been able to fix.
有發布v0.75.1了，但發布的版本有一些小問題我還沒修好，原則上正常使用是沒問題的

**Closed by lin-ycv** 2023-10-31 23:34 UTC
