### ISSUE TITLE
[BUG] Error opening file for writing

### ISSUE THREAD

**Issue by RexLuscus56** [lin-ycv/EverythingPowerToys#90] opened 2024-04-09 09:40 UTC
**Describe the bug**
On attempting to install or update to 0.80, installer errors with 
"Error opening file for writing:

C\Users\<username>\Appdata\ Local\Microsoft\PowerToys\PowerToys Run\Plugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll"

**To Reproduce**
Start the installer

**Expected behavior**
The plugin installs

**Screenshots**
N/A

**Version (please provide the version of software you are using):**
 - PowerToy: 0.80.0
 - Everything: 1.5.0.1366a (x64)
 - Windows: 11 23H2 Build 22631.3296

**Additional context**
Have tried stopping Everything tasks\services, taking ownership of the identified file to no effect

** PowerToys Run log file
[2024-04-09.txt](https://github.com/lin-ycv/EverythingPowerToys/files/14916682/2024-04-09.txt)

**Comment by lin-ycv** [comment] 2024-04-09 10:38
it's not a bug, your powertoys is still running and using the file, so the installer cannot overwrite that file.
Make sure to close powertoys, if you've already closed it and is it encountering this issue, check task manager, sometimes Powertoys can be closed, but PowerToys.Run is still open. 
Make sure these 2 processes aren't active in task manager
![image](https://github.com/lin-ycv/EverythingPowerToys/assets/60565737/358de306-d06c-4547-bf14-e38d954af3fd)
In the previous 2 version of installers, I can included logic to terminate the processes programatically, but that triggered malware warnings on some computers #81 #84 , so I removed it for this release.

**Closed by lin-ycv** 2024-04-09 10:38 UTC
Labels: bug
