### ISSUE TITLE
Plugin no longer loads with PowerToys 0.75.0 and 0.75.1

### ISSUE THREAD

**Issue by VArterJr** [lin-ycv/EverythingPowerToys#62] opened 2023-10-31 17:56 UTC
**Describe the bug**
Plugin no longer loads with PowerToys 0.75.0 and 0.75.1

**To Reproduce**
1. Upgrade PowerToys to either of the latest two builds (0.75.0 and / or 0.75.1).
2. When it launches you will see the attached pop-up stating the plugin failed to initialize.

**Expected behavior**
It would initialize. 😉

**Screenshots**
![aY2PESDAMP](https://github.com/lin-ycv/EverythingPowerToys/assets/4485488/784a6bc7-5388-4722-a391-6a1296384e67)

**Logs (please upload or provide link to you log):**
I have trimmed logs if you need them. I didn't want to send by default for privacy and security reasons.

**Version (please provide the version of software you are using):**
 - PowerToy: 0.75.1 (or 0.75.0)
 - Everything: 1.4.1.1024 (x64)
 - Windows: Win 11 Ent 22H2 Build: 22621.2506 Feature Pack: 1000.22677.1000.0

**Additional context**
You probably already know about this, but thought I would file anyway.

**Comment by Dominiquini** [comment] 2023-10-31 19:14
I found this error on the logs:

```
[2023-10-31 16:11:29.8610] [ERROR] [C:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::178]
Can't validate plugin ID of plugin <Everything> in C:\Program Files\PowerToys\RunPlugins\Everything\Community.PowerToys.Run.Plugin.Everything.dll: The static property <Main.PluginID> was not found.
```

Thanks

**Comment by lin-ycv** [comment] 2023-10-31 19:26
Duplicate of #60 
I have a working version for 0.75.x, but there's a small bug with settings, so I haven't released it yet.

**Comment by slrgt** [comment] 2023-10-31 22:46
will the update be published to the chocolately as well?

**Comment by lin-ycv** [comment] 2023-10-31 23:35
There is now a release for v0.75.1, it "works", but there's some minor buggy behaviours that I haven't been able to fix.
Chocolately releases are automatically synced with github releases, any delays are due to the chocolately review process.

**Closed by lin-ycv** 2023-10-31 23:35 UTC
Labels: bug, duplicate
